// src/config/constants.js
module.exports = {
  COLORS: {
    PRIMARY:   0xFFD618,
    SECONDARY: 0xE79D0F,
    LIGHT:     0xFEE09A,
    ACCENT:    0xF8DD54,
    DEEP:      0xBF5A08,
    DANGER:    0x661F0D,
    DARK:      0x3F0F0F,
    SUCCESS:   0x57F287,
    DISCORD:   0x1E1F22,
  },
  EMOJIS: {
    GIVEAWAY:     '🎁',
    MODERATION:   '🛡️',
    REGLEMENT:    '📜',
    WELCOME:      '👋',
    INVITES:      '📊',
    MUSIC:        '🎵',
    CONFIG:       '⚙️',
    STATS:        '📈',
    HELP:         '❓',
    DM:           '📩',
    SUCCESS:      '✅',
    ERROR:        '❌',
    WARNING:      '⚠️',
    LOADING:      '⏳',
    CROWN:        '👑',
    SWORD:        '⚔️',
    STAR:         '⭐',
    FIRE:         '🔥',
    COIN:         '🪙',
    TICKET:       '🎫',
    LOCK:         '🔒',
    UNLOCK:       '🔓',
    MEDAL_GOLD:   '🥇',
    MEDAL_SILVER: '🥈',
    MEDAL_BRONZE: '🥉',
  },
  COOLDOWNS: {
    DEFAULT:    3000,
    MUSIC:      2000,
    MODERATION: 5000,
    GIVEAWAY:   10000,
    ECONOMY:    86400000,
  },
  LIMITS: {
    PURGE_MAX:        100,
    GIVEAWAY_WINNERS: 99,
    QUEUE_MAX:        50,
    VOLUME_MAX:       200,
    DMALL_DELAY:      1500,
    WARN_BEFORE_BAN:  3,
  },
  BOT_NAME:    '⚔️ SOLARA',
  BOT_VERSION: '1.0.0',
};
